/* 
2023 - Palguno Wicaksono

The copyright holders grant the freedom to copy, modify, convey, adapt, and/or 
redistribute this work under the terms of the Massachusetts Institute of Technology License. 
A copy of that license is available at https://license.icaksh.my.id/MIT
*/

/*
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

#include <stdio.h>

int is_prime(int n)
{
    if (n < 2)
    {
        return 0;
    }
    for (size_t i = 2; i * i <= n; i++)
    {
        if (n % i == 0)
        {
            return 0;
        }
    }
    return 1;
}

int main(void)
{
    int divisors = 0;
    int triangle = 1;
    int number = 0;

    for (size_t i = 1; i <= triangle; i++)
    {
        while (divisors <= 500)
        {
            divisors = 0;
            number += triangle;
            if (is_prime(number))
            {
                triangle++;
                break;
            }
            for (size_t j = 1; j * j <= number; j++)
            {
                if (number % j == 0)
                {
                    divisors += 2;
                    printf("%d: %d\n", number, j);
                    printf("%d\n", divisors);
                }
            }
            triangle++;
        }
    }
    return 0;
}